kind: Pod 
apiVersion: v1 
metadata:
  name: pod-configmap 
spec:
  containers:
    - name: pod-configmap 
      image: nginx:1.7.9 
      envFrom:
        - configMapRef:
            name: example-configmap